# qwerty-layout
keycode  16 = w
keycode  17 = l
keycode  18 = r
keycode  19 = b
keycode  20 = z
keycode  21 = semicolon	colon
keycode  22 = q
keycode  23 = u
keycode  24 = d
keycode  25 = j
#
keycode  30 = s
keycode  31 = h
keycode  32 = n
keycode  33 = t
keycode  34 = comma	parenleft
keycode  35 = period	parenright
keycode  36 = a
keycode  37 = e
keycode  38 = o
#
keycode  44 = f
keycode  45 = m
keycode  46 = v
keycode  47 = c
keycode  48 = slash	question
keycode  49 = g
keycode  50 = p
#
include "compose"
